### ISSUE TITLE
Investigate common shared job template (and other resources) between AWX organisations

### ISSUE THREAD

**Issue by oneswig** [cedadev/jasmin-cluster-as-a-service#26]
The project and job templates should be shared across multiple organisations (in a read-only way).

This should enable admins to update a single template while the organisation-specific data is injected into the template.

**Comment by brtkwr** [comment]
Rather than having job templates replicated across organisations, here's a though:

Why not have credential type per project, e.g. `caascontrol-U credential` which injects `os_project_name` and `os_token` into the environment and allows us to run a playbook against any given project.

This gives us the ability to see where the playbooks are running for auditing and avoids us having to create lots of duplicate projects across multiple organisations.
